spring.application.name=atlasexp

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/atlasexp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Porta opcional
server.port=8080
